### ISSUE TITLE
4.3.0-classic - working version

### ISSUE THREAD

**Issue by Road-block** [niketa-wow/busyandaway#1]
[Core.lua](https://gist.github.com/Road-block/dbbe818e84b9329a463b7c3fb11265ba)

**Comment by niketa-wow** [comment]
Turns the globals are actually different between the classic and retail clients. The ones causing an issue really didn't need to be globals so I just changed to "DND" and "AFK" strings because they represent the channel which afaik shouldn't matter for locales.

If this isn't the case, I can code it based on the version instead, but I wanted to avoid that if necessary.

I decided I was bored enough to try a rewrite so I just kept that in mind on the rewrite. Listed as a beta version for the time being just to make sure there are no major issues I missed in testing, seeing as I rewrote most of the code.

Thanks.
